name: MacOS build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Normal build
      run: |
        ./configure
        make
        make clean
    - name: Unicode build
      run: |
        ./configure
        CFLAGS=-DUNICODE make
        make clean
    - name: Build with pac enabled
      run: |
        ./configure --enable-pac
        make
        make clean
    - name: Build with kerberos enabled
      run: |
        ./configure --enable-kerberos
        make
        make clean
    - name: Verify debug build
      run: |
        ./configure
        make DEBUG=1
        make clean
